# Generated by Django 3.2 on 2021-04-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.Categories'),
        ),
    ]
