# Generated by Django 3.2 on 2021-05-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210503_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
