# Generated by Django 3.2 on 2021-05-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('orders', '0003_auto_20210512_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor.vendor'),
        ),
    ]
